# This is a basic workflow that is manually triggered
name: Module Builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      helloworld:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Test scenario tags'
        required: true
        type: string
      module_name:
        description: "The module to build"
        required: true
        type: choice
        options:
          - "Module1"
          - "Module2"
          - "Module3"
          - "Module4"
        default: "Module1"
    #workflows: [Workflow Manager]
    #types: [completed]
        
run-name: Module Builder | ${{ inputs.module_name }} | ${{ inputs.helloworld }} | ${{ inputs.environment }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.helloworld }}"
