# This is a basic workflow that is manually triggered

name: App Builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      helloworld:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Test scenario tags'
        required: true
        type: string
        
run-name: App Builder | ${{ inputs.helloworld }} | ${{ inputs.environment }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.helloworld }}"
