name: Workflow Manager

on:
  schedule:
    - cron: '30 21 * * *'
    
  workflow_dispatch:
    inputs:
      builder:
        description: "Builders"
        required: true
        type: choice
        options:
          - "App Builder"
          - "Module Builder"
        default: "App Builder"
      environment:
        description: "The deployment environment"
        required: true
        type: choice
        options:
          - ""
          - "Environment1"
          - "Environment2"
          - "Environment3"
          - "Environment4"
          - "Environment5"
        default: ""
      module_name:
        description: "The deployment environment"
        required: false
        type: choice
        options:
          - ""
          - "Module1"
          - "Module2"
          - "Module3"
          - "Module4"
        default: ""
      changelog:
        description: "Built app changelog"
        required: true
        default: "Test"
        
run-name: "${{ inputs.builder }} | ${{ github.ref_name }} | ${{ inputs.environment }} | #${{ github.run_number }}"
jobs:
    job1:
        name: "Name Resolver"
        runs-on: windows-latest
        concurrency:
          group: ${{inputs.builder}}-${{ inputs.environment }}-name-resolver
        outputs:
            app_version: ${{ env.color }}
        steps:
            - id: step1
              env:
                GH_TOKEN: ${{ secrets.workflow_management }}
              if: ${{ inputs.builder == 'App Builder' }}
              run: |
                $app_builder_counters=$(gh api `
                -H "Accept: application/vnd.github+json" `
                -H "X-GitHub-Api-Version: 2022-11-28" `
                /repos/brunmmartins/GithubActionsTest/actions/variables/APP_BUILDER_COUNTER) | convertfrom-json
                $json_object = $app_builder_counters.value | convertfrom-json
                $env_counter = [int]$($json_object."${{ inputs.environment }}") + 1
                echo "color=0.1.$(Get-Date -UFormat "%j").$env_counter" >> $env:GITHUB_ENV
                $json_object | add-member -Name "${{ inputs.environment }}" -value $env_counter -MemberType NoteProperty -Force
                $json = ConvertTo-Json $json_object
                
                gh api `
                -X PATCH `
                -H "Accept: application/vnd.github+json" `
                -H "X-GitHub-Api-Version: 2022-11-28" `
                /repos/brunmmartins/GithubActionsTest/actions/variables/APP_BUILDER_COUNTER `
                -f "name=APP_BUILDER_COUNTER" -f "value=$json"
            - id: step2
              env:
                GH_TOKEN: ${{ secrets.workflow_management }}
              if: ${{ inputs.builder == 'Module Builder' && inputs.module_name != null }}
              run: |                
                $module_builder_counters=$(gh api `
                -H "Accept: application/vnd.github+json" `
                -H "X-GitHub-Api-Version: 2022-11-28" `
                /repos/brunmmartins/GithubActionsTest/actions/variables/MODULE_BUILDER_COUNTER) | convertfrom-json
                $json_object = $module_builder_counters.value | convertfrom-json
                $env_counter = [int]$($json_object."${{ inputs.module_name }}-${{ inputs.environment }}") + 1
                echo "color=0.1.$(Get-Date -UFormat "%j").$env_counter" >> $env:GITHUB_ENV
                $json_object | add-member -Name "${{ inputs.module_name }}-${{ inputs.environment }}" -value $env_counter -MemberType NoteProperty -Force
                $json = ConvertTo-Json $json_object
                
                gh api `
                -X PATCH `
                -H "Accept: application/vnd.github+json" `
                -H "X-GitHub-Api-Version: 2022-11-28" `
                /repos/brunmmartins/GithubActionsTest/actions/variables/MODULE_BUILDER_COUNTER `
                -f "name=MODULE_BUILDER_COUNTER" -f "value=$json"
    job2:
      name: ${{ needs.job1.outputs.app_version }} | ${{ inputs.environment }}
      needs: job1
      runs-on: windows-latest
      permissions:
        actions: write
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      steps:
        - id: step1
          if: ${{ inputs.builder == 'App Builder' }}
          run: |
            gh api `
              -X POST `
              -H "Accept: application/vnd.github+json" `
              -H "X-GitHub-Api-Version: 2022-11-28" `
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual.yml/dispatches `
              -f "ref=${{ github.ref_name }}" `
              -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}" `
              -f "inputs[environment]=${{ inputs.environment }}"
        - id: step2
          if: ${{ inputs.builder == 'Module Builder' && inputs.module_name != null }}
          run: |
              gh api `
              -X POST `
              -H "Accept: application/vnd.github+json" `
              -H "X-GitHub-Api-Version: 2022-11-28" `
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual2.yml/dispatches `
              -f "ref=${{ github.ref_name }}" `
              -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}" `
              -f "inputs[environment]=${{ inputs.environment }}" `
              -f "inputs[module_name]=${{ inputs.module_name }}"           
