name: Workflow Manager

on:
  schedule:
    - cron: '30 21 * * *'
    
  workflow_dispatch:
    inputs:
      builder:
        description: "Builders"
        required: true
        type: choice
        options:
          - "App Builder"
          - "Module Builder"
        default: "Builder1"
      environment:
        description: "The deployment environment"
        required: true
        type: choice
        options:
          - "Environment1"
          - "Environment2"
          - "Environment3"
          - "Environment4"
          - "Environment5"
        default: "Environment1"
      changelog:
        description: "Built app changelog"
        required: true
        default: "Test"
        
run-name: "${{ inputs.builder }} | ${{ github.ref_name }} | ${{ inputs.environment }} | #${{ github.run_number }}"

jobs:
    job1:
        name: "Name Resolver"
        runs-on: windows-latest
        outputs:
            app_version: ${{ env.color }}
        env:
          GH_TOKEN: ${{ secrets.workflow_management }}
        steps:
            - id: step1
              env: 
                app_counter: ${{ vars.APP_BUILDER_COUNTER}}
              if: ${{ inputs.builder == 'App Builder' }}
              run: |
                gh api @'
                -X "PATCH"
                -H "Accept: application/vnd.github+json"
                -H "X-GitHub-Api-Version: 2022-11-28"
                /repos/brunmmartins/GithubActionsTest/actions/variables/APP_BUILDER_COUNTER
                -f "name=APP_BUILDER_COUNTER" -f "value=$Env.app_counter++"
                '@
                echo "color=Module Builder | 0.1.$(Get-Date -UFormat "%j").${{ vars.APP_BUILDER_COUNTER }} | ${{ inputs.environment }}" >> $GITHUB_ENV
            - id: step2
              env:
                module_counter: ${{ vars.MODULE_BUILDER_COUNTER }}
              if: ${{ inputs.builder == 'Module Builder' }}
              run: |
                gh api \
                  --method PATCH \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/brunmmartins/GithubActionsTest/actions/variables/MODULE_BUILDER_COUNTER \
                  -f "name=MODULE_BUILDER_COUNTER" -f "value=$((++module_counter))"
                echo "color=Module Builder | 0.1.$(date +%j).${{ vars.MODULE_BUILDER_COUNTER }} | ${{ inputs.environment }}" >> $GITHUB_ENV
    job2:
      name: ${{ needs.job1.outputs.app_version }}
      needs: job1
      runs-on: windows-latest
      permissions:
        actions: write
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      steps:
        - id: step1
          if: ${{ inputs.builder == 'App Builder' }}
          run: |
            echo "${{ needs.job1.outputs.app_version }}"
            gh api @'
              -X POST
              -H "Accept: application/vnd.github+json"
              -H "X-GitHub-Api-Version: 2022-11-28"
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual.yml/dispatches
              -f "ref=${{ github.ref_name }}" -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}
              '@
        - id: step2
          if: ${{ inputs.builder == 'Module Builder' }}
          run: |
            echo "${{ needs.job1.outputs.app_version }}"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual2.yml/dispatches \
              -f "ref=${{ github.ref_name }}" -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}"
