name: Workflow Manager

on:
  workflow_dispatch:
  
run-name: ${{ github.job1.outputs.app_version }} 

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            app_version: ${{ steps.step1.outputs.action_state }}
        steps:
            - id: step1
              run: |
                echo "action_state=yellow" >> $GITHUB_OUTPUT
            - id: step2
              env:
                SELECTED_COLOR: ${{ steps.step1.outputs.action_state }}
              run: echo "The selected color is ${{ steps.step1.outputs.action_state }}"
    job2:
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - id: step1
          run: |
            gh workflow disable "Workflow Manager"
                
      
