name: Workflow Manager

on:
  workflow_dispatch:
    inputs:
      builder:
        description: "Builders"
        required: true
        type: choice
        options:
          - "App Builder"
          - "Module Builder"
        default: "Builder1"
      environment:
        description: "The deployment environment"
        required: true
        type: choice
        options:
          - "Environment1"
          - "Environment2"
          - "Environment3"
          - "Environment4"
          - "Environment5"
        default: "Environment1"
      changelog:
        description: "Built app changelog"
        required: true
        default: "Test"
        
run-name: "${{ inputs.builder }}-${{ github.ref_name }}-${{ inputs.environment }} | #${{ github.run_number }}"

jobs:
    job1:
        name: "Name Resolver"
        runs-on: ubuntu-latest
        outputs:
            app_version: ${{ env.color }}
        steps:
            - id: step1
              env: 
                app_counter: ${{ vars.APP_BUILDER_COUNTER}}
                GH_TOKEN: ${{ secrets.workflow_management }}
              if: ${{ inputs.builder == 'App Builder' }}
              run: |
                gh variable set APP_BUILDER_COUNTER --body $((++app_counter))
                echo "color=App Builder | 0.1.$(date +%j).${{ vars.APP_BUILDER_COUNTER}} | ${{ inputs.environment }}" >> $GITHUB_ENV
            - id: step2
              if: ${{ inputs.builder == 'Module Builder' }}
              run: |
                echo "module_builder_counter=$((++module_builder_counter))" >> $GITHUB_ENV
                echo "color=Module Builder | 0.1.$(date +%j).$module_builder_counter | ${{ inputs.environment }}" >> $GITHUB_ENV
    job2:
      name: ${{ needs.job1.outputs.app_version }}
      needs: job1
      runs-on: ubuntu-latest
      permissions:
        actions: write
      steps:
        - id: step1
          if: ${{ inputs.builder == 'App Builder' }}
          env:
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          run: |
            echo "${{ needs.job1.outputs.app_version }}"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual.yml/dispatches \
              -f "ref=${{ github.ref_name }}" -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}"
        - id: step2
          if: ${{ inputs.builder == 'Module Builder' }}
          env:
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          run: |
            echo "${{ needs.job1.outputs.app_version }}"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual2.yml/dispatches \
              -f "ref=${{ github.ref_name }}" -f "inputs[helloworld]=${{ needs.job1.outputs.app_version }}"
