name: Workflow Manager

on:
  workflow_dispatch:
  
run-name: ${{ github.job1.outputs.app_version }} 

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            app_version: ${{ steps.step1.outputs.action_state }}
        steps:
            - id: step1
              run: |
                echo "action_state=yellow" >> $GITHUB_OUTPUT
            - id: step2
              env:
                SELECTED_COLOR: ${{ steps.step1.outputs.action_state }}
              run: echo "The selected color is ${{ steps.step1.outputs.action_state }}"
    job2:
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - id: step1
          env:
            GH_TOKEN: ${{secrets.workflow_management}}
          run: |
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              #-H "Authorization: Bearer ${{ secrets.workflow_management }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/brunmmartins/GithubActionsTest/actions/workflows/manual/dispatches \
              -f "ref=main" -f "inputs[helloworld]=${{ github.job1.outputs.app_version }}"
                
      
